version: '3.8'
services:
  wildfly:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./target:/opt/jboss/wildfly/standalone/deployments
    networks:
      - mynetwork

networks:
  mynetwork:
